### ISSUE TITLE
[Question] local relative $ref

### ISSUE THREAD

**Issue by dkarlovi** [justinrainbow/json-schema#446]
I'm using this with Behat to validate a JSON response for APIs. Using 5.2.1.

If my schema is embedded inside a Behat feature file (say `features/my.feature`), how do I reference a definition inside `schemas/entity.json`? Would that definition be able to reference some other definition (`schemas/other-entity.json`)?

**Comment by erayd** [comment]
Local references within the same document must start with `/`, where `/` refers to the root of the schema in which the `$ref` occurs.

If you're wanting to refer to another file, then you simply concatenate the file and the reference to the part of the file you wish to reference, separated by `#`. For example, `"$ref": "schemas/other-entity.json#/definitions/my/entity"`. If you want to reference the entire file, then the filename alone is sufficient.

There is no limit to how many layers of referencing you can use. Definitions are dereferenced as needed during validation.

**Comment by dkarlovi** [comment]
@erayd Thank you very much for such a quick reply! :+1: 

Let's just use an example to be more clear, sorry about the verbosity:

1) I have a schema embedded into Behat feature file `features/my.feature`:

```yaml
    Scenario: Fetching a list of existing images when images match
        When I send a "GET" request to "/api/images"
        Then the JSON should be valid according to this schema:
        """
        {
            "definitions": {
                "user": {
                    "type": "object",
                    "required": ["id", "username"],
                    "properties": {
                        "id": {"type": "string", "format": "udid"},
                        "username": {"type": "string"}
                    },
                    "additionalProperties": false
                },
                "image": {
                    "type": "object",
                    "required": ["id", "name"],
                    "properties": {
                        "id": {"type": "string", "format": "udid"},
                        "name": {"type": "string"},
                        "created_at": {"type": "string", "format": "date-time"},
                        "created_by": {"$ref": "#/definitions/user"},
                        "updated_at": {"type": "string", "format": "date-time"},
                        "updated_by": {"$ref": "#/definitions/user"}
                    },
                    "additionalProperties": false
                }
            },
            "type": "array",
            "items": {"$ref": "#/definitions/image"},
            "minItems": 30,
            "maxItems": 30,
            "uniqueItems": true,
            "additionalItems": false
        }
        """
```
2) I'd like to extract `user` and `image definitions` to `schemas/user.json` and `schemas/image.json`, ie.
```json
{
  "title": "user",
  "type": "object",
  "required": ["id", "username"],
  "properties": {
    "id": {"type": "string", "format": "udid"},
    "username": {"type": "string"}
  },
  "additionalProperties": false
}
```

```json
{
  "title": "image",
  "type": "object",
  "required": ["id", "name"],
  "properties": {
    "id": {"type": "string", "format": "udid"},
    "name": {"type": "string"},
    "created_at": {"type": "string", "format": "date-time"},
    "created_by": {"$ref": "user.json"},
    "updated_at": {"type": "string", "format": "date-time"},
    "updated_by": {"$ref": "user.json"}
  },
  "additionalProperties": false
}
```
3. this would make my feature file more dry and makes writing tests much easier:
```yaml
    Scenario: Fetching a list of existing images when images match
        When I send a "GET" request to "/api/images"
        And the JSON should be valid according to this schema:
        """
        {
            "type": "array",
            "items": {"$ref": "image.json"},
            "minItems": 30,
            "maxItems": 30,
            "uniqueItems": true,
            "additionalItems": false
        }
        """

Obviously, this doesn't work currently so my questions is how would one do this properly?
