### ISSUE TITLE
undefinedConstraint problem

### ISSUE THREAD

**Issue by aWuttig** [justinrainbow/json-schema#546]
Hey,

i have the following json schema definition.

```
          schema:
            type: object
            properties:
              id:
                type: integer
              test:
                type: string
                format: uuid
```
and my json is

```
{
  "foo": "bar"
}
```
When i run validation i get no errors?!?! But why... The json is definetly wrong.

I found out that the undefinedConstraint from here https://github.com/justinrainbow/json-schema/blob/3921012b92bdda17ec9b5a9f62cd25b2d0591b70/src/JsonSchema/Constraints/ObjectConstraint.php#L141 is the reason for that behaviour.

When i use null for undefinedConstraint it works perfectly. Why do you do this constraint? Do i miss something...
